importacion de librerias

In [43]:
import polars as pl
import matplotlib as plt
import numpy as np
import json

escaneo de datos

In [44]:


data_training = pl.scan_csv("datasets/train.csv")
head_10 = data_training.head(10).collect()
pl.Config.set_tbl_rows(-1)
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(10_000)
pl.Config.set_fmt_str_lengths(1_000)
print(head_10)

shape: (10, 18)
┌──────────────┬──────────────┬───────────────────────┬──────────────────┬──────────────────────┬────────────────────────────┬─────────────────────────────┬───────────────┬────────────┬───────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬─────────────────┬─────────────────┬───────────┬──────────────────────────────────────────────────────────────────┬─────────────┬──────────────────┐
│ item_id      ┆ user_id      ┆ region                ┆ city             ┆ parent_category_name ┆ category_name              ┆ param_1                     ┆ param_2       ┆ param_3    ┆ title                                         ┆ description                                                                                                                                   ┆ price   ┆ item_seq_number ┆ activation_date ┆ user_type ┆ image                                                            ┆ image_top_1 ┆ deal_probability │
│ ---          ┆ ---          ┆ ---                   ┆ ---              ┆ ---                  ┆ ---                        ┆ ---                         ┆ ---           ┆ ---        ┆ ---                                           ┆ ---                                                                                                                                           ┆ ---     ┆ ---             ┆ ---             ┆ ---       ┆ ---                                                              ┆ ---         ┆ ---              │
│ str          ┆ str          ┆ str                   ┆ str              ┆ str                  ┆ str                        ┆ str                         ┆ str           ┆ str        ┆ str                                           ┆ str                                                                                                                                           ┆ f64     ┆ i64             ┆ str             ┆ str       ┆ str                                                              ┆ f64         ┆ f64              │
╞══════════════╪══════════════╪═══════════════════════╪══════════════════╪══════════════════════╪════════════════════════════╪═════════════════════════════╪═══════════════╪════════════╪═══════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═════════╪═════════════════╪═════════════════╪═══════════╪══════════════════════════════════════════════════════════════════╪═════════════╪══════════════════╡
│ b912c3c6a6ad ┆ e00f8ff2eaf9 ┆ Свердловская область  ┆ Екатеринбург     ┆ Личные вещи          ┆ Товары для детей и игрушки ┆ Постельные принадлежности   ┆ null          ┆ null       ┆ Кокоби(кокон для сна)                         ┆ Кокон для сна малыша,пользовались меньше месяца.цвет серый                                                                                    ┆ 400.0   ┆ 2               ┆ 2017-03-28      ┆ Private   ┆ d10c7e016e03247a3bf2d13348fe959fe6f436c1caf64c7679f17c333c959b19 ┆ 1008.0      ┆ 0.12789          │
│ 2dac0150717d ┆ 39aeb48f0017 ┆ Самарская область     ┆ Самара           ┆ Для дома и дачи      ┆ Мебель и интерьер          ┆ Другое                      ┆ null          ┆ null       ┆ Стойка для Одежды                             ┆ Стойка для одежды, под вешалки. С бутика.                                                                                                     ┆ 3000.0  ┆ 19              ┆ 2017-03-26      ┆ Private   ┆ 79c9392cc51a9c81c6eb91eceb8e552171db39d71427001e1e0859c0fb843a31 ┆ 692.0       ┆ 0.0              │
│ ba83aefab5dc ┆ 91e2f88dd6e3 ┆ Ростовская область    ┆ Ростов-на-Дону   ┆ Бытовая электроника  ┆ Аудио и видео              ┆ Видео, DVD и Blu-ray плееры ┆ null          ┆ null       ┆ Philips bluray                                ┆ В хорошем состоянии, домашний кинотеатр с blu ray, USB. Если настроить, то работает смарт тв /                                                ┆ 4000.0  ┆ 9               ┆ 2017-03-20      ┆ Private   ┆ b7f250ee3f39e1fedd77c141f273703f4a9be59db4b48a8713f112c67e29bb42 ┆ 3032.0      ┆ 0.43177          │
│              ┆              ┆                       ┆                  ┆                      ┆                            ┆                             ┆               ┆            ┆                                               ┆ Торг                                                                                                                                          ┆         ┆                 ┆                 ┆           ┆                                                                  ┆             ┆                  │
│ 02996f1dd2ea ┆ bf5cccea572d ┆ Татарстан             ┆ Набережные Челны ┆ Личные вещи          ┆ Товары для детей и игрушки ┆ Автомобильные кресла        ┆ null          ┆ null       ┆ Автокресло                                    ┆ Продам кресло от0-25кг                                                                                                                        ┆ 2200.0  ┆ 286             ┆ 2017-03-25      ┆ Company   ┆ e6ef97e0725637ea84e3d203e82dadb43ed3cc0a1c841302bf49820803501b4b ┆ 796.0       ┆ 0.80323          │
│ 7c90be56d2ab ┆ ef50846afc0b ┆ Волгоградская область ┆ Волгоград        ┆ Транспорт            ┆ Автомобили                 ┆ С пробегом                  ┆ ВАЗ (LADA)    ┆ 2110       ┆ ВАЗ 2110, 2003                                ┆ Все вопросы по телефону.                                                                                                                      ┆ 40000.0 ┆ 3               ┆ 2017-03-16      ┆ Private   ┆ 54a687a3a0fc1d68aed99bdaaf551c5c70b761b16fd0a2c089d8376e883ed33b ┆ 2264.0      ┆ 0.20797          │
│ 51e0962387f7 ┆ bbfad0b1ad0a ┆ Татарстан             ┆ Чистополь        ┆ Личные вещи          ┆ Товары для детей и игрушки ┆ Автомобильные кресла        ┆ null          ┆ null       ┆ Авто люлька                                   ┆ В хорошем состоянии                                                                                                                           ┆ 1300.0  ┆ 9               ┆ 2017-03-28      ┆ Private   ┆ eb6ad1231c59d3dc7e4020e724ffe8e4d302023ddcbb99c52a6117994dd44690 ┆ 796.0       ┆ 0.80323          │
│ c4f260a2b48a ┆ 08f469d2e6f7 ┆ Нижегородская область ┆ Нижний Новгород  ┆ Для дома и дачи      ┆ Ремонт и строительство     ┆ Сантехника и сауна          ┆ null          ┆ null       ┆ Водонагреватель 100 литров нержавейка плоский ┆ Электро водонагреватель накопительный на 100 литров Термекс ID 100V, плоский, внутренний бак из нержавейки, 2 кВт, б/у 2 недели, на гарантии. ┆ 11000.0 ┆ 125             ┆ 2017-03-23      ┆ Private   ┆ 0330f6ac561f5db1fa8226dd5e7e127b5671d44d075a9801ec9e6ee9d20ad2c6 ┆ 2823.0      ┆ 0.0              │
│ 6b71309d6a8a ┆ fef86baa002c ┆ Пермский край         ┆ Пермь            ┆ Личные вещи          ┆ Одежда, обувь, аксессуары  ┆ Женская одежда              ┆ Джинсы        ┆ 26         ┆ Бойфренды colins                              ┆ Бойфренды в хорошем состоянии.                                                                                                                ┆ 500.0   ┆ 61              ┆ 2017-03-25      ┆ Private   ┆ 9bab29a519e81c14f4582024adfebd4f11a4ac71d323a62f7731e19db9702115 ┆ 567.0       ┆ 0.80323          │
│ c5b969cb63a2 ┆ 055825270190 ┆ Оренбургская область  ┆ Оренбург         ┆ Личные вещи          ┆ Одежда, обувь, аксессуары  ┆ Женская одежда              ┆ Платья и юбки ┆ > 50 (XXL) ┆ Платье                                        ┆ 54 раз мер очень удобное                                                                                                                      ┆ 500.0   ┆ 85              ┆ 2017-03-17      ┆ Private   ┆ 75ce06d1f939a31dfb2af8ac55f08fa998fa336d13ee05326eb44166d47a8aed ┆ 415.0       ┆ 0.0              │
│ b1570962e68c ┆ f9e8f831d94c ┆ Нижегородская область ┆ Нижний Новгород  ┆ Личные вещи          ┆ Детская одежда и обувь     ┆ Для девочек                 ┆ Обувь         ┆ 25         ┆ Полу ботиночки замш натур.Бамбини             ┆ По стельке 15.5см мерить приокский район. Цвет темнее чем на фото                                                                             ┆ 400.0   ┆ 136             ┆ 2017-03-22      ┆ Company   ┆ 54fb8521135fda77a860bfd2fac6bf46867ab7c06796e3e3636587c101e10301 ┆ 46.0        ┆ 0.0              │
└──────────────┴──────────────┴───────────────────────┴──────────────────┴──────────────────────┴────────────────────────────┴─────────────────────────────┴───────────────┴────────────┴───────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴─────────────────┴─────────────────┴───────────┴──────────────────────────────────────────────────────────────────┴─────────────┴──────────────────┘

examinamos el esquema

In [45]:
schema = data_training.collect_schema()
#print(schema)
print(json.dumps(
    {columna: str(tipo) for columna, tipo in schema.items()},
    indent=2,
    ensure_ascii=False
))

{
  "item_id": "String",
  "user_id": "String",
  "region": "String",
  "city": "String",
  "parent_category_name": "String",
  "category_name": "String",
  "param_1": "String",
  "param_2": "String",
  "param_3": "String",
  "title": "String",
  "description": "String",
  "price": "Float64",
  "item_seq_number": "Int64",
  "activation_date": "String",
  "user_type": "String",
  "image": "String",
  "image_top_1": "Float64",
  "deal_probability": "Float64"
}

vemos cuantas filas y columnas hay

In [46]:
row_count = data_training.select(pl.len().alias("rows")).collect().item()
columns_count = schema.len()
print(f"cantidad de filas: {row_count}")
print(f"cantidad de columnas: {columns_count}")

cantidad de filas: 1503424
cantidad de columnas: 18

contamos en promedio los valores nulos por cada columna

In [47]:
missing_share = data_training.select(
    pl.all().is_null().mean()
).collect()

missing_share

shape: (1, 18)
┌─────────┬─────────┬────────┬──────┬──────────────────────┬───────────────┬──────────┬──────────┬──────────┬───────┬─────────────┬──────────┬─────────────────┬─────────────────┬───────────┬──────────┬─────────────┬──────────────────┐
│ item_id ┆ user_id ┆ region ┆ city ┆ parent_category_name ┆ category_name ┆ param_1  ┆ param_2  ┆ param_3  ┆ title ┆ description ┆ price    ┆ item_seq_number ┆ activation_date ┆ user_type ┆ image    ┆ image_top_1 ┆ deal_probability │
│ ---     ┆ ---     ┆ ---    ┆ ---  ┆ ---                  ┆ ---           ┆ ---      ┆ ---      ┆ ---      ┆ ---   ┆ ---         ┆ ---      ┆ ---             ┆ ---             ┆ ---       ┆ ---      ┆ ---         ┆ ---              │
│ f64     ┆ f64     ┆ f64    ┆ f64  ┆ f64                  ┆ f64           ┆ f64      ┆ f64      ┆ f64      ┆ f64   ┆ f64         ┆ f64      ┆ f64             ┆ f64             ┆ f64       ┆ f64      ┆ f64         ┆ f64              │
╞═════════╪═════════╪════════╪══════╪══════════════════════╪═══════════════╪══════════╪══════════╪══════════╪═══════╪═════════════╪══════════╪═════════════════╪═════════════════╪═══════════╪══════════╪═════════════╪══════════════════╡
│ 0.0     ┆ 0.0     ┆ 0.0    ┆ 0.0  ┆ 0.0                  ┆ 0.0           ┆ 0.040957 ┆ 0.435368 ┆ 0.573734 ┆ 0.0   ┆ 0.077341    ┆ 0.056778 ┆ 0.0             ┆ 0.0             ┆ 0.0       ┆ 0.074888 ┆ 0.074888    ┆ 0.0              │
└─────────┴─────────┴────────┴──────┴──────────────────────┴───────────────┴──────────┴──────────┴──────────┴───────┴─────────────┴──────────┴─────────────────┴─────────────────┴───────────┴──────────┴─────────────┴──────────────────┘

contamos exactamente cuantos valores nulos hay

In [48]:
missing_share = data_training.select(
    pl.all().null_count()
).collect()

missing_share

shape: (1, 18)
┌─────────┬─────────┬────────┬──────┬──────────────────────┬───────────────┬─────────┬─────────┬─────────┬───────┬─────────────┬───────┬─────────────────┬─────────────────┬───────────┬────────┬─────────────┬──────────────────┐
│ item_id ┆ user_id ┆ region ┆ city ┆ parent_category_name ┆ category_name ┆ param_1 ┆ param_2 ┆ param_3 ┆ title ┆ description ┆ price ┆ item_seq_number ┆ activation_date ┆ user_type ┆ image  ┆ image_top_1 ┆ deal_probability │
│ ---     ┆ ---     ┆ ---    ┆ ---  ┆ ---                  ┆ ---           ┆ ---     ┆ ---     ┆ ---     ┆ ---   ┆ ---         ┆ ---   ┆ ---             ┆ ---             ┆ ---       ┆ ---    ┆ ---         ┆ ---              │
│ u32     ┆ u32     ┆ u32    ┆ u32  ┆ u32                  ┆ u32           ┆ u32     ┆ u32     ┆ u32     ┆ u32   ┆ u32         ┆ u32   ┆ u32             ┆ u32             ┆ u32       ┆ u32    ┆ u32         ┆ u32              │
╞═════════╪═════════╪════════╪══════╪══════════════════════╪═══════════════╪═════════╪═════════╪═════════╪═══════╪═════════════╪═══════╪═════════════════╪═════════════════╪═══════════╪════════╪═════════════╪══════════════════╡
│ 0       ┆ 0       ┆ 0      ┆ 0    ┆ 0                    ┆ 0             ┆ 61576   ┆ 654542  ┆ 862565  ┆ 0     ┆ 116276      ┆ 85362 ┆ 0               ┆ 0               ┆ 0         ┆ 112588 ┆ 112588      ┆ 0                │
└─────────┴─────────┴────────┴──────┴──────────────────────┴───────────────┴─────────┴─────────┴─────────┴───────┴─────────────┴───────┴─────────────────┴─────────────────┴───────────┴────────┴─────────────┴──────────────────┘